name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

env:
  LIBSSL: "libssl1.1_1.1.1f-1ubuntu2_amd64.deb"

jobs:
  get_chip_name:
    runs-on: ubuntu-latest
    outputs:
      chip_name: ${{ steps.capture.outputs.chip_name }}
    steps:
      - uses: cargo-bins/cargo-binstall@main

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            libssl*.deb
          key: ${{ runner.os }}-libssl

      - name: Install libssl
        run: |
          [ ! -f $LIBSSL ] && wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/$LIBSSL
          sudo dpkg -i $LIBSSL

      - name: Install rmkit v0.0.16
        run: cargo binstall rmkit@0.0.16 -y

      - name: Get chip name
        id: capture
        run: |
          OUTPUT=$(rmkit get-chip --keyboard-toml-path ${{ inputs.keyboard_toml_path }})
          echo "Command output: $OUTPUT"
          echo "chip_name=$OUTPUT" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: get_chip_name
    if: needs.get_chip_name.outputs.chip_name != 'esp32s3'
    steps:
      - uses: cargo-bins/cargo-binstall@main
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            libssl*.deb
          key: ${{ runner.os }}-libssl

      - name: Install libssl
        run: |
          [ ! -f $LIBSSL ] && wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/$LIBSSL
          sudo dpkg -i $LIBSSL

      - name: Install rmkit v0.0.16, flip-link, cargo-make
        run: cargo binstall cargo-make rmkit@0.0.16 flip-link -y

      - name: Create firmware project
        run: rmkit create --keyboard-toml-path keyboard.toml --vial-json-path vial.json --target-dir rmk

      - name: Build firmware
        working-directory: ./rmk
        run: cargo build --release

      - name: Build uf2 firmware
        working-directory: ./rmk
        run: cargo make uf2 --release

      - name: Upload artifacts (UF2)
        uses: actions/upload-artifact@v4
        with:
          name: firmware_uf2
          path: rmk/*.uf2

      - name: Upload artifacts (HEX)
        uses: actions/upload-artifact@v4
        with:
          name: firmware_hex
          path: rmk/*.hex

  build_esp:
    runs-on: ubuntu-latest
    needs: get_chip_name
    if: needs.get_chip_name.outputs.chip_name == 'esp32s3'
    steps:
      - uses: cargo-bins/cargo-binstall@main
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            libssl*.deb
          key: ${{ runner.os }}-libssl

      - name: Install libssl
        run: |
          [ ! -f $LIBSSL ] && wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/$LIBSSL
          sudo dpkg -i $LIBSSL

      - name: Install rmkit v0.0.16, espflash, espup
        run: cargo binstall rmkit@0.0.16 espflash espup -y

      - name: Prepare esp environment
        run: espup install

      - name: Create firmware project
        run: rmkit create --keyboard-toml-path keyboard.toml --vial-json-path vial.json --target-dir rmk

      - name: Build firmware for ESP32
        working-directory: ./rmk
        run: . /home/runner/export-esp.sh && cargo +esp build --release

      - name: Get target arch
        id: arch
        run: |
          if [ "${{ needs.get_chip_name.outputs.chip_name }}" == "esp32c3" ]; then
            ARCH="riscv32imc-unknown-none-elf"
          elif [ "${{ needs.get_chip_name.outputs.chip_name }}" == "esp32s3" ]; then
            ARCH="xtensa-esp32s3-none-elf"
          elif [ "${{ needs.get_chip_name.outputs.chip_name }}" == "esp32c6" ]; then
            ARCH="riscv32imac-unknown-none-elf"
          else
            ARCH=""
          fi
          echo "arch=$ARCH" >> $GITHUB_OUTPUT

      - name: Get project name
        id: project_name
        run: |
          OUTPUT=$(rmkit get-project-name --keyboard-toml-path keyboard.toml)
          echo "Command output: $OUTPUT"
          echo "project_name=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Convert firmware to bin
        working-directory: ./rmk
        run: espflash save-image --chip ${{ needs.get_chip_name.outputs.chip_name }} target/${{ steps.arch.outputs.arch }}/release/${{ steps.project_name.outputs.project_name }} ./rmk.bin

      - name: Upload artifacts (BIN)
        uses: actions/upload-artifact@v4
        with:
          name: firmware_bin
          path: rmk/*.bin
